version: "3.9"

services:
  api:
    container_name: file-service
    build:
      context: .            # 레포 루트에 Dockerfile이 있을 때
      dockerfile: Dockerfile
    env_file:
      - .env                # EC2에만 존재(.git에 올리지 않음)
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MULTIPART_MAX_FILE_SIZE: ${MULTIPART_MAX_FILE_SIZE}
      MULTIPART_MAX_REQUEST_SIZE: ${MULTIPART_MAX_REQUEST_SIZE}
      TZ: Asia/Seoul
    ports:
      - "8080:8080"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
